[
  { startCity: "Białystok", endCity: "Olsztyn", distance: 210 },
  { startCity: "Białystok", endCity: "Warszawa", distance: 132 },
  { startCity: "Białystok", endCity: "Lublin", distance: 226 },
  { startCity: "Białystok", endCity: "Bydgoszcz", distance: 306 },
  { startCity: "Białystok", endCity: "Gdańsk", distance: 289 },
  { startCity: "Białystok", endCity: "Łódź", distance: 209 },
  { startCity: "Białystok", endCity: "Poznań", distance: 306 },
  { startCity: "Białystok", endCity: "Szczecin", distance: 448 },
  { startCity: "Białystok", endCity: "Gorzów Wielkopolski", distance: 391 },
  { startCity: "Białystok", endCity: "Wrocław", distance: 333 },
  { startCity: "Białystok", endCity: "Opole", distance: 343 },
  { startCity: "Białystok", endCity: "Katowice", distance: 309 },
  { startCity: "Białystok", endCity: "Kielce", distance: 247 },
  { startCity: "Białystok", endCity: "Kraków", distance: 327 },
  { startCity: "Białystok", endCity: "Rzeszów", distance: 320 },
  { startCity: "Olsztyn", endCity: "Warszawa", distance: 161 },
  { startCity: "Olsztyn", endCity: "Lublin", distance: 263 },
  { startCity: "Olsztyn", endCity: "Bydgoszcz", distance: 187 },
  { startCity: "Olsztyn", endCity: "Gdańsk", distance: 114 },
  { startCity: "Olsztyn", endCity: "Łódź", distance: 211 },
  { startCity: "Olsztyn", endCity: "Poznań", distance: 268 },
  { startCity: "Olsztyn", endCity: "Szczecin", distance: 367 },
  { startCity: "Olsztyn", endCity: "Gorzów Wielkopolski", distance: 353 },
  { startCity: "Olsztyn", endCity: "Wrocław", distance: 335 },
  { startCity: "Olsztyn", endCity: "Opole", distance: 350 },
  { startCity: "Olsztyn", endCity: "Katowice", distance: 316 },
  { startCity: "Olsztyn", endCity: "Kielce", distance: 273 },
  { startCity: "Olsztyn", endCity: "Kraków", distance: 353 },
  { startCity: "Olsztyn", endCity: "Rzeszów", distance: 355 },
  { startCity: "Warszawa", endCity: "Lublin", distance: 118 },
  { startCity: "Warszawa", endCity: "Bydgoszcz", distance: 200 },
  { startCity: "Warszawa", endCity: "Gdańsk", distance: 229 },
  { startCity: "Warszawa", endCity: "Łódź", distance: 104 },
  { startCity: "Warszawa", endCity: "Poznań", distance: 198 },
  { startCity: "Warszawa", endCity: "Szczecin", distance: 340 },
  { startCity: "Warszawa", endCity: "Gorzów Wielkopolski", distance: 283 },
  { startCity: "Warszawa", endCity: "Wrocław", distance: 225 },
  { startCity: "Warszawa", endCity: "Opole", distance: 228 },
  { startCity: "Warszawa", endCity: "Katowice", distance: 193 },
  { startCity: "Warszawa", endCity: "Kielce", distance: 128 },
  { startCity: "Warszawa", endCity: "Kraków", distance: 209 },
  { startCity: "Warszawa", endCity: "Rzeszów", distance: 207 },
  { startCity: "Lublin", endCity: "Bydgoszcz", distance: 286 },
  { startCity: "Lublin", endCity: "Gdańsk", distance: 341 },
  { startCity: "Lublin", endCity: "Łódź", distance: 189 },
  { startCity: "Lublin", endCity: "Poznań", distance: 287 },
  { startCity: "Lublin", endCity: "Szczecin", distance: 429 },
  { startCity: "Lublin", endCity: "Gorzów Wielkopolski", distance: 372 },
  { startCity: "Lublin", endCity: "Wrocław", distance: 314 },
  { startCity: "Lublin", endCity: "Opole", distance: 319 },
  { startCity: "Lublin", endCity: "Katowice", distance: 248 },
  { startCity: "Lublin", endCity: "Kielce", distance: 148 },
  { startCity: "Lublin", endCity: "Kraków", distance: 211 },
  { startCity: "Lublin", endCity: "Rzeszów", distance: 114 },
  { startCity: "Bydgoszcz", endCity: "Gdańsk", distance: 116 },
  { startCity: "Bydgoszcz", endCity: "Łódź", distance: 155 },
  { startCity: "Bydgoszcz", endCity: "Poznań", distance: 97 },
  { startCity: "Bydgoszcz", endCity: "Szczecin", distance: 219 },
  { startCity: "Bydgoszcz", endCity: "Gorzów Wielkopolski", distance: 183 },
  { startCity: "Bydgoszcz", endCity: "Wrocław", distance: 197 },
  { startCity: "Bydgoszcz", endCity: "Opole", distance: 254 },
  { startCity: "Bydgoszcz", endCity: "Katowice", distance: 258 },
  { startCity: "Bydgoszcz", endCity: "Kielce", distance: 262 },
  { startCity: "Bydgoszcz", endCity: "Kraków", distance: 312 },
  { startCity: "Bydgoszcz", endCity: "Rzeszów", distance: 380 },
  { startCity: "Gdańsk", endCity: "Łódź", distance: 206 },
  { startCity: "Gdańsk", endCity: "Poznań", distance: 197 },
  { startCity: "Gdańsk", endCity: "Szczecin", distance: 262 },
  { startCity: "Gdańsk", endCity: "Gorzów Wielkopolski", distance: 281 },
  { startCity: "Gdańsk", endCity: "Wrocław", distance: 295 },
  { startCity: "Gdańsk", endCity: "Opole", distance: 345 },
  { startCity: "Gdańsk", endCity: "Katowice", distance: 311 },
  { startCity: "Gdańsk", endCity: "Kielce", distance: 314 },
  { startCity: "Gdańsk", endCity: "Kraków", distance: 365 },
  { startCity: "Gdańsk", endCity: "Rzeszów", distance: 422 },
  { startCity: "Łódź", endCity: "Poznań", distance: 143 },
  { startCity: "Łódź", endCity: "Szczecin", distance: 282 },
  { startCity: "Łódź", endCity: "Gorzów Wielkopolski", distance: 226 },
  { startCity: "Łódź", endCity: "Wrocław", distance: 145 },
  { startCity: "Łódź", endCity: "Opole", distance: 167 },
  { startCity: "Łódź", endCity: "Katowice", distance: 137 },
  { startCity: "Łódź", endCity: "Kielce", distance: 139 },
  { startCity: "Łódź", endCity: "Kraków", distance: 193 },
  { startCity: "Łódź", endCity: "Rzeszów", distance: 274 },
  { startCity: "Poznań", endCity: "Szczecin", distance: 168 },
  { startCity: "Poznań", endCity: "Gorzów Wielkopolski", distance: 109 },
  { startCity: "Poznań", endCity: "Wrocław", distance: 127 },
  { startCity: "Poznań", endCity: "Opole", distance: 182 },
  { startCity: "Poznań", endCity: "Katowice", distance: 232 },
  { startCity: "Poznań", endCity: "Kielce", distance: 260 },
  { startCity: "Poznań", endCity: "Kraków", distance: 286 },
  { startCity: "Poznań", endCity: "Rzeszów", distance: 368 },
  { startCity: "Szczecin", endCity: "Gorzów Wielkopolski", distance: 73 },
  { startCity: "Szczecin", endCity: "Wrocław", distance: 247 },
  { startCity: "Szczecin", endCity: "Opole", distance: 289 },
  { startCity: "Szczecin", endCity: "Katowice", distance: 337 },
  { startCity: "Szczecin", endCity: "Kielce", distance: 402 },
  { startCity: "Szczecin", endCity: "Kraków", distance: 391 },
  { startCity: "Szczecin", endCity: "Rzeszów", distance: 473 },
  { startCity: "Gorzów Wielkopolski", endCity: "Wrocław", distance: 187 },
  { startCity: "Gorzów Wielkopolski", endCity: "Opole", distance: 229 },
  { startCity: "Gorzów Wielkopolski", endCity: "Katowice", distance: 278 },
  { startCity: "Gorzów Wielkopolski", endCity: "Kielce", distance: 342 },
  { startCity: "Gorzów Wielkopolski", endCity: "Kraków", distance: 332 },
  { startCity: "Gorzów Wielkopolski", endCity: "Rzeszów", distance: 414 },
  { startCity: "Wrocław", endCity: "Opole", distance: 81 },
  { startCity: "Wrocław", endCity: "Katowice", distance: 129 },
  { startCity: "Wrocław", endCity: "Kielce", distance: 252 },
  { startCity: "Wrocław", endCity: "Kraków", distance: 183 },
  { startCity: "Wrocław", endCity: "Rzeszów", distance: 265 },
  { startCity: "Opole", endCity: "Katowice", distance: 83 },
  { startCity: "Opole", endCity: "Kielce", distance: 210 },
  { startCity: "Opole", endCity: "Kraków", distance: 138 },
  { startCity: "Opole", endCity: "Rzeszów", distance: 220 },
  { startCity: "Katowice", endCity: "Kielce", distance: 132 },
  { startCity: "Katowice", endCity: "Kraków", distance: 67 },
  { startCity: "Katowice", endCity: "Rzeszów", distance: 148 },
  { startCity: "Kielce", endCity: "Kraków", distance: 100 },
  { startCity: "Kielce", endCity: "Rzeszów", distance: 145 },
  { startCity: "Kraków", endCity: "Rzeszów", distance: 112 },
  { startCity: "Olsztyn", endCity: "Białystok", distance: 210 },
  { startCity: "Warszawa", endCity: "Białystok", distance: 132 },
  { startCity: "Lublin", endCity: "Białystok", distance: 226 },
  { startCity: "Bydgoszcz", endCity: "Białystok", distance: 306 },
  { startCity: "Gdańsk", endCity: "Białystok", distance: 289 },
  { startCity: "Łódź", endCity: "Białystok", distance: 209 },
  { startCity: "Poznań", endCity: "Białystok", distance: 306 },
  { startCity: "Szczecin", endCity: "Białystok", distance: 448 },
  { startCity: "Gorzów Wielkopolski", endCity: "Białystok", distance: 391 },
  { startCity: "Wrocław", endCity: "Białystok", distance: 333 },
  { startCity: "Opole", endCity: "Białystok", distance: 343 },
  { startCity: "Katowice", endCity: "Białystok", distance: 309 },
  { startCity: "Kielce", endCity: "Białystok", distance: 247 },
  { startCity: "Kraków", endCity: "Białystok", distance: 327 },
  { startCity: "Rzeszów", endCity: "Białystok", distance: 320 },
  { startCity: "Warszawa", endCity: "Olsztyn", distance: 161 },
  { startCity: "Lublin", endCity: "Olsztyn", distance: 263 },
  { startCity: "Bydgoszcz", endCity: "Olsztyn", distance: 187 },
  { startCity: "Gdańsk", endCity: "Olsztyn", distance: 114 },
  { startCity: "Łódź", endCity: "Olsztyn", distance: 211 },
  { startCity: "Poznań", endCity: "Olsztyn", distance: 268 },
  { startCity: "Szczecin", endCity: "Olsztyn", distance: 367 },
  { startCity: "Gorzów Wielkopolski", endCity: "Olsztyn", distance: 353 },
  { startCity: "Wrocław", endCity: "Olsztyn", distance: 335 },
  { startCity: "Opole", endCity: "Olsztyn", distance: 350 },
  { startCity: "Katowice", endCity: "Olsztyn", distance: 316 },
  { startCity: "Kielce", endCity: "Olsztyn", distance: 273 },
  { startCity: "Kraków", endCity: "Olsztyn", distance: 353 },
  { startCity: "Rzeszów", endCity: "Olsztyn", distance: 355 },
  { startCity: "Lublin", endCity: "Warszawa", distance: 118 },
  { startCity: "Bydgoszcz", endCity: "Warszawa", distance: 200 },
  { startCity: "Gdańsk", endCity: "Warszawa", distance: 229 },
  { startCity: "Łódź", endCity: "Warszawa", distance: 104 },
  { startCity: "Poznań", endCity: "Warszawa", distance: 198 },
  { startCity: "Szczecin", endCity: "Warszawa", distance: 340 },
  { startCity: "Gorzów Wielkopolski", endCity: "Warszawa", distance: 283 },
  { startCity: "Wrocław", endCity: "Warszawa", distance: 225 },
  { startCity: "Opole", endCity: "Warszawa", distance: 228 },
  { startCity: "Katowice", endCity: "Warszawa", distance: 193 },
  { startCity: "Kielce", endCity: "Warszawa", distance: 128 },
  { startCity: "Kraków", endCity: "Warszawa", distance: 209 },
  { startCity: "Rzeszów", endCity: "Warszawa", distance: 207 },
  { startCity: "Bydgoszcz", endCity: "Lublin", distance: 286 },
  { startCity: "Gdańsk", endCity: "Lublin", distance: 341 },
  { startCity: "Łódź", endCity: "Lublin", distance: 189 },
  { startCity: "Poznań", endCity: "Lublin", distance: 287 },
  { startCity: "Szczecin", endCity: "Lublin", distance: 429 },
  { startCity: "Gorzów Wielkopolski", endCity: "Lublin", distance: 372 },
  { startCity: "Wrocław", endCity: "Lublin", distance: 314 },
  { startCity: "Opole", endCity: "Lublin", distance: 319 },
  { startCity: "Katowice", endCity: "Lublin", distance: 248 },
  { startCity: "Kielce", endCity: "Lublin", distance: 148 },
  { startCity: "Kraków", endCity: "Lublin", distance: 211 },
  { startCity: "Rzeszów", endCity: "Lublin", distance: 114 },
  { startCity: "Bydgoszcz", endCity: "Gdańsk", distance: 116 },
  { startCity: "Łódź", endCity: "Gdańsk", distance: 206 },
  { startCity: "Poznań", endCity: "Gdańsk", distance: 197 },
  { startCity: "Szczecin", endCity: "Gdańsk", distance: 262 },
  { startCity: "Gorzów Wielkopolski", endCity: "Gdańsk", distance: 281 },
  { startCity: "Wrocław", endCity: "Gdańsk", distance: 295 },
  { startCity: "Opole", endCity: "Gdańsk", distance: 345 },
  { startCity: "Katowice", endCity: "Gdańsk", distance: 311 },
  { startCity: "Kielce", endCity: "Gdańsk", distance: 314 },
  { startCity: "Kraków", endCity: "Gdańsk", distance: 365 },
  { startCity: "Rzeszów", endCity: "Gdańsk", distance: 422 },
  { startCity: "Łódź", endCity: "Poznań", distance: 143 },
  { startCity: "Szczecin", endCity: "Poznań", distance: 168 },
  { startCity: "Gorzów Wielkopolski", endCity: "Poznań", distance: 109 },
  { startCity: "Wrocław", endCity: "Poznań", distance: 127 },
  { startCity: "Opole", endCity: "Poznań", distance: 182 },
  { startCity: "Katowice", endCity: "Poznań", distance: 232 },
  { startCity: "Kielce", endCity: "Poznań", distance: 260 },
  { startCity: "Kraków", endCity: "Poznań", distance: 286 },
  { startCity: "Rzeszów", endCity: "Poznań", distance: 368 },
  { startCity: "Gorzów Wielkopolski", endCity: "Szczecin", distance: 73 },
  { startCity: "Wrocław", endCity: "Szczecin", distance: 247 },
  { startCity: "Opole", endCity: "Szczecin", distance: 289 },
  { startCity: "Katowice", endCity: "Szczecin", distance: 337 },
  { startCity: "Kielce", endCity: "Szczecin", distance: 402 },
  { startCity: "Kraków", endCity: "Szczecin", distance: 391 },
  { startCity: "Rzeszów", endCity: "Szczecin", distance: 473 },
  { startCity: "Gorzów Wielkopolski", endCity: "Wrocław", distance: 187 },
  { startCity: "Opole", endCity: "Wrocław", distance: 81 },
  { startCity: "Katowice", endCity: "Wrocław", distance: 129 },
  { startCity: "Kielce", endCity: "Wrocław", distance: 252 },
  { startCity: "Kraków", endCity: "Wrocław", distance: 183 },
  { startCity: "Rzeszów", endCity: "Wrocław", distance: 265 },
  { startCity: "Katowice", endCity: "Opole", distance: 83 },
  { startCity: "Kielce", endCity: "Opole", distance: 210 },
  { startCity: "Kraków", endCity: "Opole", distance: 138 },
  { startCity: "Rzeszów", endCity: "Opole", distance: 220 },
  { startCity: "Katowice", endCity: "Kielce", distance: 132 },
  { startCity: "Kraków", endCity: "Katowice", distance: 67 },
  { startCity: "Rzeszów", endCity: "Katowice", distance: 148 },
  { startCity: "Kielce", endCity: "Kraków", distance: 100 },
  { startCity: "Rzeszów", endCity: "Kraków", distance: 112 },
  { startCity: "Kielce", endCity: "Rzeszów", distance: 145 },
];
